version: 1
disable_existing_loggers: true

formatters:
  simple:
    style: '{'
    format: 'SIMPLE FORMATTER: {asctime} - {name} - {levelname} - {message}'

handlers:
  console:
    formatter: simple
    class: logging.StreamHandler
    stream: ext://sys.stdout

loggers:
  root:
    level: DEBUG
    handlers: [console]

  app:
    level: INFO